[general]
#import = ["~/.config/alacritty/themes/tomorrow_night_bright.toml"]
#import = ["~/.config/alacritty/themes/alabaster_dark.toml"]
#import = ["~/.config/alacritty/themes/github_dark_high_contrast.toml"]
import = ["~/.config/alacritty/themes/ayu_dark.toml"]

[window]
padding.x = 0
padding.y = 0
decorations = "none"
opacity = 0.98
blur = true

[font]
normal = {family = "ZedMono Nerd Font", style = "regular"}
bold = {family = "ZedMono Nerd Font", style = "Bold"}
italic = {family = "ZedMono Nerd Font", style = "Italic"}
size = 15

[cursor]
style.shape = "Block"
style.blinking = "on"
